### ISSUE TITLE
please update to 1.20.1

### ISSUE THREAD

**Issue by bloodmasked** [infernalstudios/Celestial-Configuration#5]
thank you

**Comment by BodhiSmith13** [comment]
![Screenshot 2024-05-30 201114](https://github.com/infernalstudios/Celestial-Configuration/assets/86609495/e99a80be-7b0a-4b0b-910a-7f991a6777cd)

**Comment by tinytransfem** [comment]
all versions from 1.20.1 to 1.21 are now supported
