### ISSUE TITLE
The Stars Have Frozen 

### ISSUE THREAD

**Issue by BodhiSmith13** [infernalstudios/Celestial-Configuration#7]
Celestial Configuration for Forge 1.20.1 causes the stars to freeze in the sky:
https://medal.tv/games/minecraft/clips/hYfrIGPCgnR7ulLB6/d13374uTjlOi?invite=cr-MSxhancsMzMwNjk5MzQs
Forge Version: 47.2.19

**Comment by SwanX1** [comment]
Please provide a full modlist, as well as try reproducing the issue without any resource packs or shaders enabled.

**Comment by BodhiSmith13** [comment]
The original video was with a custom modpack, but the issue persists even with only this mod installed without resourcepacks or shaders.

**Comment by Mabra51** [comment]
I'm having the same issue, it's like the skybox is following your view.

**Comment by tinytransfem** [comment]
fixed in version 1.1.1
